name: Daily Azure Blob Upload

on:
  schedule:
    - cron: '0 8 * * *'  # 8:00 AM UTC = 10:00 AM CEST (July 2025, DST)
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Paris  # Ensures CET/CEST compatibility
    permissions:
      id-token: write  # Required for OIDC
      contents: read   # Required to checkout repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yfinance python-dotenv

      - name: Generate report
        env:
          METAL_API_KEY: ${{ secrets.METAL_API_KEY }}
          BLOB_STORAGE_BASE_URL: ${{ secrets.BLOB_STORAGE_BASE_URL }}
        run: python scripts/generate_report.py

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to Azure Blob Storage
        uses: azure/storage-blob-upload@v1
        with:
          account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          container-name: $web
          source-path: dist/
          destination-path: /
          overwrite: true