name: Monthly Currency Report

on:
  schedule:
    - cron: '0 8 9 * *'  # Runs monthly
  workflow_dispatch:     # Allows manual run

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests yfinance tabulate

    - name: Run report script
      env:
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python scripts/currency_report_v2.py